name: CI/CD Pipeline

on:
  push:
    branches:
      - main
env:
  AWS_REGION: "us-east-1"  
  
  contents: read
    
jobs:
  tf-fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
     
        - name: Checkout Repo
          uses: actions/checkout@v3

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.6.2 
        
        - name: Terraform Init
          uses: docker://hashicorp/terraform:1.6.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TF_ACTION_WORKING_DIR: 'terraform'
            AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: Terraform Validate
          uses: hashicorp/terraform-github-actions/validate@v0.3.7

        - name: Terraform Apply
          uses: hashicorp/terraform-github-actions/apply@v0.4.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TF_ACTION_WORKING_DIR: 'terraform'
            AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - name: Checkout Repository
      #   uses: actions/checkout@v2

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 1.0.0

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     TF_ACTION_WORKING_DIR: 'terraform'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - name: Get Lambda Function URL
          run: echo "Lambda Function URL:${{ steps.deploy.outputs.url }}"

